config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  put 'home/update_profile'
  get 'home/edit_password'
  put 'home/update_password'
  get 'session/show_login'
  post 'session/login'
  get 'session/logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  put 'user_password/:id', to: 'users#reset_password', as: :reset_password
  
  resources :users, :articles
  resources :tags, except: :show
  
  
  get 'blog/:id', to: 'blog#show' ,as: :blog_show
  get 'blogs/:user_id', to: 'blog#index', as: :blog_index
  get 'author/:id', to: 'blog#author', as: :author_show
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_tags
  has_many :tags, through: :article_tags
  has_one_attached :picture
  belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    if helpers.is_super?
      @articles = Article.all
    else
      @articles = Article.where("user_id = ?", session[:user_id])
    end
  end
  
  def new
  end
  
  def create
    @article = Article.new article_params.slice(:title,:content,:picture)
    @article.user_id = session[:user_id]
    @article.tag_ids = article_params[:tag_ids]
    if @article.save
      redirect_to articles_url
    else
      flash[:success] = "创建文章失败"
      render 'new'
    end
  end
  
  def show
    @article = Article.find params[:id]
    if @article.nil?
      flash[:info] = "无法找到文章"
    end
    if @article.user_id != session[:user_id] && !helpers.is_super?
      redirect_back fallback_location: articles_url
    end
  end
  
  def article_params
    params.except('authenticity_token').permit(:title,:content,:picture,:tag_ids=>[])
  end
  
  def destroy
    article = Article.find params[:id]
    if !helpers.is_super? && article.user_id != session[:user_id]
        session[:waring] = "您无权删除该文章"
        redirect_back fallback_location: articles_url
    end
    if Article.delete(params[:id])
      flash[:info] = "删除失败"
      redirect_back fallback_location: articles_url
    else
      redirect_to articles_url
    end
    
  end
  
  def edit
    @article = Article.find_by_id params[:id]
    if @article.user_id != session[:user_id] && !helpers.is_super?
      # 如果既不是作者也不是超级管理员，则不给编辑
        session[:waring] = "您无权编辑"
        redirect_back fallback_location: articles_url
    end
  end
  
  def update
    @article = Article.find params[:id]
    if !helpers.is_super? && @article.user_id != session[:user_id]
        session[:waring] = "您无权编辑"
        redirect_back fallback_location: articles_url
    end
    @article.update article_params
    flash[:success] = "编辑文章成功"
    redirect_to articles_url
  end
  
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <!--        <form method="post" action="<%#= users_url %>">-->
        <%= form_tag article_path(@article.id), method: :put ,multipart: true do %>
          <div class="card-header">
            <h4 class="card-title">
              编辑
            </h4>
          </div>
          <div class="card-content">
            <div class="form-group">
              <!--              <label>标题</label>-->
              <%= label_tag "title", "名称" %>
              <!--              <input name="title" type="text" placeholder="请输入文章标题" class="form-control">-->
              <%= text_field_tag "title", @article.title, placeholder: "请输入文章标题", class: "form-control" %>
            </div>
            <div class="form-group">
              <!--              <label>邮箱</label>-->
              <%= label_tag "content", "内容" %>
              <!--              <input name="content" type="email" placeholder="请输入文章" class="form-control">-->
              <%= text_area_tag "content", @article.content, placeholder: "请填写文章内容", class: "form-control", rows:5 %>
            </div>

            <div class="form-group">
              <%= label_tag "picture", "图片" %>
              <%= file_field_tag "picture", class: "form-control" %>
            </div>
            <div class="form-group">
              <label>标签</label>
              <select multiple title="Multiple Select" class="selectpicker" data-style="btn-info btn-fill btn-block" data-size="7" name="tag_ids[]">
                <%= options_from_collection_for_select Tag.all, 'id', 'name', @article.tags.map{|tag| tag.id}  %>
              </select>
            </div>
            <button type="submit" class="btn btn-fill btn-info">Submit</button>
          </div>
        <% end %>
        <!--        </form>-->
      </div> <!-- end card -->
    </div> <!--  end col-md-6  -->

  </div> <!-- end row -->
</div>

app/views/articles/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Table with Links</h4>
          <p class="category">Here is a subtitle for this table</p>
        </div>
        <div class="card-content table-responsive table-full-width">
          <table class="table">
            <thead>
            <tr>
              <th class="text-center">ID</th>
              <th>标题</th>
              <th>内容</th>
              <th>配图</th>
              <th>标签</th>
              <th>作者</th>
              <th>创建时间</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <% @articles.each do |article| %>
              <tr>
                <td class="text-center"><%= article.id %></td>
                <td><%= article.title %></td>
                <td>
                  <% content = article.content; if content.size > 27 %>
                    <%= content[0, 26] + '...' %>
                  <% else %>
                    <%= content %>
                  <% end %>
                </td>
                <td>
                  <% if article.picture.attached? %>
                    <div class="image-container">
                      <%= image_tag article.picture.variant(resize_to_limit: [200, 200]) %>
                    </div>
                  <% end %>
                </td>
                <td>
                  <% unless article.tags.empty? %>
                    <%= article.tags.map { |tag| tag.name }.join(',') %>
                  <% end %>

                </td>
                <td><%= article.user.username %></td>
                <td><%= article.created_at %></td>
                <td class="td-actions text-right">
                  <!--                                <a href="#" rel="tooltip" title="View Profile" class="btn btn-info btn-simple btn-xs">-->
                  <!--                                  <i class="ti-user"></i>-->
                  <!--                                </a>-->
                  <!--                                <a href="#" rel="tooltip" title="Edit Profile" class="btn btn-success btn-simple btn-xs">-->
                  <!--                                  <i class="ti-pencil-alt"></i>-->
                  <!--                                </a>-->
                  <!--                                <a href="<%#= link_to %>>" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">-->
                  <!--                                  <i class="ti-close"></i>-->
                  <!--                                </a>-->
                  <%= link_to "详情", article_path(article.id) %>
                  <%= link_to "编辑", edit_article_path(article.id) %>
                  <%= link_to "删除", article_path(article.id), method: :delete %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <!--        <form method="post" action="<%#= users_url %>">-->
        <%= form_tag articles_path, method: :post ,multipart: true do %>
          <div class="card-header">
            <h4 class="card-title">
              新建文章
            </h4>
          </div>
          <div class="card-content">
            <div class="form-group">
              <!--              <label>标题</label>-->
              <%= label_tag "title", "名称" %>
              <!--              <input name="title" type="text" placeholder="请输入文章标题" class="form-control">-->
              <%= text_field_tag "title", nil, placeholder: "请输入文章标题", class: "form-control" %>
            </div>
            <div class="form-group">
              <!--              <label>邮箱</label>-->
              <%= label_tag "content", "内容" %>
              <!--              <input name="content" type="email" placeholder="请输入文章" class="form-control">-->
              <%= text_area_tag "content", nil, placeholder: "请填写文章内容", class: "form-control", rows:5 %>
            </div>

            <div class="form-group">
              <%= label_tag "picture", "图片" %>
              <%= file_field_tag "picture", class: "form-control" %>
            </div>
            <div class="form-group">
              <label>标签</label>
              <select multiple title="Multiple Select" class="selectpicker" data-style="btn-info btn-fill btn-block" data-size="7" name="tag_ids[]">
                <%= options_from_collection_for_select Tag.all, 'id', 'name'  %>
              </select>
            </div>
            <button type="submit" class="btn btn-fill btn-info">Submit</button>
          </div>
        <% end %>
        <!--        </form>-->
      </div> <!-- end card -->
    </div> <!--  end col-md-6  -->

  </div> <!-- end row -->
</div>

app/views/articles/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Paper Dashboard Headings</h4>
          <p class="category">Created using <a href="https://www.google.com/fonts/specimen/Muli">Muli</a> Font Family</p>
        </div>
        <div class="card-content">
          <div class="typo-line">
            <h3><p class="category">标题</p><%= @article.title %></h3>
          </div>
          <div class="typo-line">
            <p><span class="category">内容</span><%= @article.content %></p>
          </div>
          <div class="typo-line">
            <p class="category">配图</p><div class="row">
            <% if @article.picture.attached? %>
              <div class="image-container">
                <%= image_tag @article.picture.variant(resize_to_limit: [200, 400]) %>
              </div>
            <% end %>
          </div>
          </div>
          <div class="typo-line">
            <h5><p class="category">作者</p><%= @article.user.username %></h5>
          </div>
          <div class="typo-line">
            <h5><p class="category">创建日期</p><%= @article.created_at %></h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>