config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  put 'home/update_profile'
  get 'home/edit_password'
  put 'home/update_password'
  get 'session/show_login'
  post 'session/login'
  get 'session/logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  put 'user_password/:id', to: 'users#reset_password', as: :reset_password
  
  resources :users, :articles
  resources :tags, except: :show
  
  
  get 'blog/:id', to: 'blog#show' ,as: :blog_show
  get 'blogs/:user_id', to: 'blog#index', as: :blog_index
  get 'author/:id', to: 'blog#author', as: :author_show
end

app/models/user.rb
# require 'bcrypt'
class User < ApplicationRecord
  include BCrypt
  validates_confirmation_of :password
  has_many :articles
  # 用户头像
  has_one_attached :avatar
  # 用户的博客背景
  has_one_attached :background
  # 返回的实际上是进一步处理过的密码
  def password
    @password ||= Password.new(password_hash)
  end
  
  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_super
  def new
  
  end

  def create
    @user = User.new user_params
    @user.password = "123456" #给用户设置一个初始密码
    if @user.save
      flash[:success] = "创建用户成功"
      redirect_to users_url
    else
      render 'new'
    end
  end
  
  def update
    user = User.find_by_id params[:id]
    if user.nil?
      flash[:info] = "无法找到指定的用户"
      redirect_back fallback_location: users_url
      return
    end
    if user.id == 1
      flash[:info] = "该用户无法被更新"
      redirect_back fallback_location: users_url
      return
    end
    if user.update user_params
      flash[:success] = "更新用户信息成功"
    else
      flash[:danger] = "更新用户信息失败"
    end
    redirect_to users_url
  end
  
  def edit
  
  end
  
  
  def index
    @users = User.all
  end
  
  def destroy
    user = User.find_by_id params[:id]
    if user.nil?
      flash[:info] = '无法找到指定的用户'
      redirect_back fallback_location: users_url
      return
    end
    if user.id == 1
      flash[:info] = "该用户无法被删除"
      redirect_back fallback_location: users_url
      return
    end
    if user.delete
      flash[:success] = "删除用户成功"
    else
      flash[:danger] = "删除用户失败"
    end
    redirect_to users_url
  end
  
  def show
  
  end
  
  def user_params
    params.except('authenticity_token')
      .permit(
        :username,
        # :password,
        :email,
        :profession,
        :avatar,
        :background,
        :introduction
      )
  end
  
  
  def reset_password
    @user = User.find_by_id params[:id]
    if @user.nil?
      flash[:warning] = "无法找到指定的用户，请确认该用户是否存在"
      redirect_back fallback_location: users_url
      return
    end
    @user.password = 123456
    unless user.save
      flash[:danger] = "重设用户密码失败"
      redirect_back fallback_location: users_url
      return
    end
    flash[:sucess] = "重设用户密码成功"
    redirect_to users_url
  end
  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Table with Links</h4>
          <p class="category">Here is a subtitle for this table</p>
        </div>
        <div class="card-content table-responsive table-full-width">
          <table class="table">
            <thead>
            <tr>
              <th class="text-center">ID</th>
              <th>用户名</th>
              <th>邮箱</th>
              <th>职业</th>
              <th>头像</th>
              <th>背景图片</th>
              <th>个人简介</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
            <tr>
              <td class="text-center"><%= user.id %></td>
              <td><%= user.username %></td>
              <td><%= user.email %></td>
              <td><%= user.profession %></td>
              <td>
                <% if user.avatar.attached? %>
                  <div class="img-container">
                    <%= image_tag user.avatar.variant resize_to_limit: [200, 200] %>
                  </div>
                <% end %>
                  </td>
              <td>
                <% if user.background.attached? %>
                  <div class="img-container">
                    <%= image_tag user.background.variant(resize_to_limit: [200, 200]) %>
                  </div>
                <% end %>
              </td>
              <td><%= user.introduction %></td>
              <td class="td-actions text-right">
<!--                <a href="#" rel="tooltip" title="View Profile" class="btn btn-info btn-simple btn-xs">-->
<!--                  <i class="ti-user"></i>-->
<!--                </a>-->
<!--                <a href="#" rel="tooltip" title="Edit Profile" class="btn btn-success btn-simple btn-xs">-->
<!--                  <i class="ti-pencil-alt"></i>-->
<!--                </a>-->
<!--                <a href="#" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">-->
<!--                  <i class="ti-close"></i>-->
<!--                </a>-->
                <%= link_to "重置密码", reset_password_path(user.id), method: :put %>
              </td>
            </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6">
            <div class="card">
<!--              <form method="post" action="<%#= users_url %>">-->
                <%= form_tag users_path, method: :post, multipart: true do %>
                <div class="card-header">
                  <h4 class="card-title">
                    创建用户
                  </h4>
                </div>
                <div class="card-content">
                  <div class="form-group">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                    <%= label_tag "username", "用户名" %>
<!--                    <label>用户名</label>-->
<!--                    <input name="username" type="text" placeholder="请输入用户姓名" class="form-control">-->
                    <%= text_field_tag "username",nil, placeholder: "请输入用户名", class: "form-control" %>
                  </div>
                  <div class="form-group">
<!--                    <label>邮箱</label>-->
                    <%= label_tag "email", "邮箱" %>
<!--                    <input name="email" type="email" placeholder="请输入用户邮箱" class="form-control">-->
                    <%= text_field_tag "email", nil, placeholder: "请输入用户邮箱", class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= label_tag "profession", "职业"%>
                    <%= text_field_tag "profession", nil, placeholder: "请输入用户的职业", class: "form-control" %>
                  </div>
<!--                  <div class="form-group">-->
<!--                    <label>密码</label>-->
                    <%#= label_tag "password", "密码" %>
<!--                    <input name="password" type="text" placeholder="请输入用户密码" class="form-control">-->
                    <%#= text_field_tag "password", nil, placeholder: '请输入用户密码', class: "form-control" %>
<!--                  </div>-->
                  <div class="form-group">
                    <%= label_tag "用户头像" %>
                    <%= file_field_tag "avatar", class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= label_tag "背景图片" %>
                    <%= file_field_tag "background", class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= label_tag "introduction", "个人简介" %>
<!--                    <label>个人简介</label>-->
<!--                      <textarea name="introduction"class="form-control" placeholder="请填写该用户的个人简介" rows="3"></textarea>-->
                    <%= text_area_tag "password", nil, placeholder: "请填写该用户的个人简介",class: "form-control", rows: 3 %>
                  </div>
<!--                  <div class="form-group">-->
<!--                    <label class="checkbox">-->
<!--                      <input type="checkbox" data-toggle="checkbox" value="" checked>-->
<!--                      Subscribe to newsletter-->
<!--                    </label>-->
<!--                  </div>-->
                  <%= button_tag "提交", type: "submit", class: "btn btn-fill btn-info" %>
<!--                  <button type="submit" class="btn btn-fill btn-info">Submit</button>-->
                </div>
                <% end %>
<!--              </form>-->
            </div> <!-- end card -->
          </div> <!--  end col-md-6  -->

        </div> <!-- end row -->
      </div>