config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  put 'home/update_profile'
  get 'home/edit_password'
  put 'home/update_password'
  get 'session/show_login'
  post 'session/login'
  get 'session/logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  put 'user_password/:id', to: 'users#reset_password', as: :reset_password
  
  resources :users, :articles
  resources :tags, except: :show
  
  
  get 'blog/:id', to: 'blog#show' ,as: :blog_show
  get 'blogs/:user_id', to: 'blog#index', as: :blog_index
  get 'author/:id', to: 'blog#author', as: :author_show
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.find session[:user_id]
    # 显示个人信息
    # 显示文章数量信息
    # 显示浏览信息
    # 用户信息包括，邮箱，手机号，个人简介, 职业
  end
  
  def edit_password
    @user = User.find session[:user_id]
  end
  
  def update_password
    user = User.find(session[:user_id])
    if user.update params.permit(:password, :password_confirmation)
      flash[:success] = "修改密码成功"
      redirect_to home_index_url
    else
      flash[:danger] = "修改密码失败"
      redirect_back fallback_location: home_index_url
    end
  end
  
  
  def update_profile
    @user = User.find(session[:user_id])
    if @user.nil?
      flash[:warning] = "无法找到用户信息"
      redirect_back fallback_location: home_index_url
      return
    end
    if @user.update params.permit(:email, :profession, :avatar, :background, :introduction)
      flash[:success] = "更新用户信息成功"
      redirect_to home_index_url
    else
      redirect_back fallback_location: home_index_url
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/edit_password.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <!--              <form method="post" action="<%#= users_url %>">-->
        <%= form_tag home_update_password_path, method: :put, multipart: true do %>
          <div class="card-header">
            <h4 class="card-title">
              修改密码
            </h4>
          </div>
          <div class="card-content">
            <div class="form-group">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
              <%= label_tag "username", "用户名" %>
              <!--                    <label>用户名</label>-->
              <!--                    <input name="username" type="text" placeholder="请输入用户姓名" class="form-control">-->
              <%= text_field_tag "username",@user.username, placeholder: "请输入用户名", class: "form-control", disabled: true %>
            </div>
            <div class="form-group">
              <%= label_tag "password","用户密码"%>
              <%= password_field_tag "password",nil, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= label_tag "password_confirmation", "确认密码"%>
              <%= password_field_tag "password_confirmation", nil, class: "form-control" %>
            </div>
            <%= button_tag "提交", type: "submit", class: "btn btn-fill btn-info" %>
<!--                              <button type="submit" class="btn btn-fill btn-info">Submit</button>-->
          </div>
        <% end %>
        <!--              </form>-->
      </div> <!-- end card -->
    </div> <!--  end col-md-6  -->

  </div> <!-- end row -->
</div>

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4 col-md-5">
      <div class="card card-user">
        <div class="image">
<!--          <img src="../../assets/img/background.jpg" alt="..."/>-->
          <% if @user.avatar.attached? %>
              <%= image_tag @user.background.variant auto_orient: true %>
          <% end %>
        </div>
        <div class="card-content">
          <div class="author">
<!--            <img class="avatar border-white" src="../../assets/img/faces/face-2.jpg" alt="..."/>-->
            <%= image_tag @user.avatar.variant(auto_orient: true), class: "avatar border-white" %>
            <h4 class="card-title"><%= @user.username %><br />
              <a href="#"><small><%= @user.email %></small></a>
            </h4>
          </div>
<!--          <p class="description text-center">-->
<!--            "I like the way you work it <br>-->
<!--            No diggity <br>-->
<!--            I wanna bag it up"-->
<!--          </p>-->
        </div>
        <hr>
        <div class="text-center">
          <div class="row">
            <div class="col-md-4 col-md-offset-2">
              <h5><%= @user.articles.size %><br /><small>文章</small></h5>
            </div>
            <div class="col-md-4">
              <h5>0<br /><small>浏览数</small></h5>
            </div>
<!--            <div class="col-md-3">-->
<!--              <h5>24,6$<br /><small>Spent</small></h5>-->
<!--            </div>-->
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-8 col-md-7">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">编辑个人信息</h4>
        </div>
        <div class="card-content">
          <%= form_tag home_update_profile_path, method: :put, multipart: true do %>
<!--          <form>-->
<!--            <div class="row">-->
              <div class="form-group">
                <%= label_tag "username", "用户名" %>
                <%= text_field_tag "username", @user.username, class: "form-control border-input", disabled: true %>
              </div>
              <div class="form-group">
                <%= label_tag "email", "邮箱" %>
                <%= text_field_tag "email", @user.email, class: "form-control border-input"  %>
              </div>
              <div class="form-group">
                <%= label_tag "profession", "职业" %>
                <%= text_field_tag "profession", @user.profession, class: "form-control border-input" %>
              </div>
              <div class="form-group">
                <%= label_tag "avatar", "头像" %>
                <%= file_field_tag "avatar", class: "form-control" %>
              </div>
              <div class="form-group">
                <%= label_tag "background", "背景图片" %>
                <%= file_field_tag "background", class: "form-control" %>
              </div>
              <div class="form-group">
                <%= label_tag "introduction", "个人简介" %>
                <%= text_area_tag "introduction", @user.introduction, class: "form-control border-input", rows: 3 %>
              </div>
<!--              <div class="form-control">-->
                <button type="submit" class="btn btn-info btn-fill btn-wd">更新用户信息</button>
<!--              </div>-->
<!--            </div>-->
<!--            <div class="clearfix"></div>-->
<!--          </form>-->
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>