config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  put 'home/update_profile'
  get 'home/edit_password'
  put 'home/update_password'
  get 'session/show_login'
  post 'session/login'
  get 'session/logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  put 'user_password/:id', to: 'users#reset_password', as: :reset_password
  
  resources :users, :articles
  resources :tags, except: :show
  
  
  get 'blog/:id', to: 'blog#show' ,as: :blog_show
  get 'blogs/:user_id', to: 'blog#index', as: :blog_index
  get 'author/:id', to: 'blog#author', as: :author_show
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :articles, through: :article_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  before_action :require_super
  def new
  
  end
  
  def create
    @tag = Tag.new params.permit(:name,:remark)
    if @tag.save
      flash[:success] = "创建标签成功"
      redirect_to tags_url
    else
      render 'new'
    end
  end
  
  
  def index
    @tags = Tag.all
  end
  
  def edit
    @tag = Tag.find_by_id params[:id]
    if @tag.nil?
      flash[:info] = "无法找到制定的标签"
      redirect_back fallback_location: tags_url
    end
  end
  
  def update
    @tag = Tag.find_by_id params[:id]
    if @tag.nil?
      redirect_back fallback_location: tags_url
    end
    @tag.update tag_params
    flash[:success] = '编辑标签成功'
    redirect_to tags_url
  end
  
  def destroy
    @tag = Tag.find_by_id params[:id]
    if @tag.nil?
      flash[:info] = "无法找到该标签，删除失败"
      redirect_back fallback_location: tags_url
      return
    end
    if @tag.articles.size > 0
      flash[:danger] = "该标签下仍有关联文章，无法删除"
      redirect_back fallback_location: tags_url
      return
    end
    unless @tag.delete
      flash[:success] = "删除成功"
      redirect_back fallback_location: tags_url
      return
    end
    redirect_to tags_url
  end
  
  def tag_params
    params.except('authenticity_token').permit(:name, :mark)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <!--        <form method="post" action="<%#= users_url %>">-->
        <%= form_tag tag_path(@tag.id), method: :put do %>
          <div class="card-header">
            <h4 class="card-title">
              编辑标签
            </h4>
          </div>
          <div class="card-content">
            <div class="form-group">
              <%#= hidden_field_tag :authenticity_token, form_authenticity_token -%>
              <!--              <label>标签名称</label>-->
              <%= label_tag "tag_name", "名称" %>
              <!--              <input name="name" type="text" placeholder="请输入标签名称" class="form-control">-->
              <%= text_field_tag "name",@tag.name, class: "form-control", placeholder: "请输入标签名称" %>
            </div>
            <div class="form-group">
              <!--              <label>备注</label>-->
              <%= label_tag "tag_remark", '备注' %>
              <!--              <input name="remark" type="text" placeholder="请输入标签备注" class="form-control">-->
              <%= text_field_tag "remark",@tag.remark, class: "form-control", placeholder: "请输入标签备注" %>
            </div>
            <!--            <button type="submit" class="btn btn-fill btn-info">提交</button>-->
            <%= button_tag "提交", type: "submit", class: "btn btn-fill btn-info" %>
          </div>
        <% end %>
        <!--        </form>-->
      </div> <!-- end card -->
    </div> <!--  end col-md-6  -->

  </div> <!-- end row -->
</div>

app/views/tags/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">标签列表</h4>
<!--          <p class="category">Here is a subtitle for this table</p>-->
        </div>
        <div class="card-content table-responsive table-full-width">
          <table class="table">
            <thead>
            <tr>
              <th class="text-center">ID</th>
              <th>标签名称</th>
              <th>备注</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <% @tags.each do |tag| %>
              <tr>
                <td class="text-center"><%= tag.id %></td>
                <td><%= tag.name %></td>
                <td><%= tag.remark %></td>
                <td>
                  <%= link_to "编辑", edit_tag_path(tag.id) %>
                  <%= link_to "删除", tag_path(tag.id), method: :delete %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tags/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
<!--        <form method="post" action="<%#= users_url %>">-->
        <%= form_tag tags_url, method: "post" do %>
          <div class="card-header">
            <h4 class="card-title">
              创建标签
            </h4>
          </div>
          <div class="card-content">
            <div class="form-group">
              <%#= hidden_field_tag :authenticity_token, form_authenticity_token -%>
<!--              <label>标签名称</label>-->
              <%= label_tag "tag_name", "名称" %>
<!--              <input name="name" type="text" placeholder="请输入标签名称" class="form-control">-->
              <%= text_field_tag "name",nil, class: "form-control", placeholder: "请输入标签名称" %>
            </div>
            <div class="form-group">
<!--              <label>备注</label>-->
              <%= label_tag "tag_remark", '备注' %>
<!--              <input name="remark" type="text" placeholder="请输入标签备注" class="form-control">-->
              <%= text_field_tag "remark",nil, class: "form-control", placeholder: "请输入标签备注" %>
            </div>
<!--            <button type="submit" class="btn btn-fill btn-info">提交</button>-->
            <%= button_tag "提交", type: "submit", class: "btn btn-fill btn-info" %>
          </div>
          <% end %>
<!--        </form>-->
      </div> <!-- end card -->
    </div> <!--  end col-md-6  -->

  </div> <!-- end row -->
</div>